# =============================================================================
# Cloud Build configuration for Laravel on Cloud Run
# =============================================================================

steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest"
      - "."
    id: "build"

  # Push the Docker image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}"
    id: "push"
    waitFor: ["build"]

  # Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--add-cloudsql-instances"
      - "${_CLOUD_SQL_CONNECTION}"
      - "--set-env-vars"
      - "APP_NAME=Loyalty Point API,APP_ENV=production,APP_DEBUG=false,APP_URL=https://${_SERVICE_NAME}-258075006047.${_REGION}.run.app,LOG_CHANNEL=stderr,LOG_LEVEL=warning,DB_CONNECTION=mysql,DB_SOCKET=/cloudsql/${_CLOUD_SQL_CONNECTION},DB_DATABASE=loyalty_point,DB_USERNAME=loyalty_user,SESSION_DRIVER=database,SESSION_SECURE_COOKIE=true,CACHE_STORE=database,QUEUE_CONNECTION=database,MAIL_MAILER=smtp,MAIL_HOST=smtp.gmail.com,MAIL_PORT=587,MAIL_USERNAME=wafaapp01@gmail.com,MAIL_ENCRYPTION=tls,MAIL_FROM_ADDRESS=wafaapp01@gmail.com,MAIL_FROM_NAME=Loyalty Point API"
      - "--set-secrets"
      - "APP_KEY=APP_KEY:latest,DB_PASSWORD=DB_PASSWORD:latest,MAIL_PASSWORD=MAIL_PASSWORD:latest"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "10"
      - "--concurrency"
      - "80"
      - "--timeout"
      - "300s"
      - "--cpu-boost"
      - "--no-cpu-throttling"
    id: "deploy"
    waitFor: ["push"]

# Substitution variables (override in trigger or command line)
substitutions:
  _REGION: "me-central1"
  _REPOSITORY: "loyalty-point"
  _SERVICE_NAME: "loyalty-point-api"
  _CLOUD_SQL_CONNECTION: "${PROJECT_ID}:${_REGION}:loyalty-point-db"

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

# Build timeout
timeout: "1200s"

# Images to store in Artifact Registry
images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest"
